import path from 'node:path';
import { copyDir, ensureDir, readTextIfExists, upsertManagedBlock, writeTextIfChanged } from '../../utils/fs.mjs';
import { readTemplate } from '../../core/templates.mjs';

export const id = 'kimi';
export const name = 'Kimi';
export const homeDir = '~/.kimi';
export const supports = { skills: true, commands: true, config: true };

export async function installSkills(sourceDir, { replace = false } = {}) {
  const targetDir = path.join(homeDir, 'skills', path.basename(sourceDir));
  await ensureDir(path.dirname(targetDir));
  return copyDir(sourceDir, targetDir);
}

export async function installCommands(commands, { replace = false } = {}) {
  if (!commands?.length) return [];
  const results = [];
  for (const command of commands) {
    const content = await readTemplate(`templates/kimi/command-${command}.md`).catch(() => null);
    if (!content) continue;
    results.push(await writeTextIfChanged(path.join(homeDir, 'commands', `${command}.md`), content));
  }
  return results;
}

export async function installConfig({ replace = false } = {}) {
  const configPath = path.join(homeDir, 'config.toml');
  const managed = `# Threadline-managed config for Kimi\n# Kimi knowledge graph and project docs are generated by Threadline.\n`;
  if (replace) {
    return [await writeTextIfChanged(configPath, managed.trimEnd() + '\n')];
  }
  return [await upsertManagedBlock(configPath, 'THREADLINE_MANAGED', managed)];
}

export async function adopt() {
  const findings = [];
  findings.push(await inspectPath('kimi-skill', path.join(homeDir, 'skills', 'threadline', 'SKILL.md')));
  findings.push(await inspectPath('kimi-config', path.join(homeDir, 'config.toml')));
  return findings;
}

export async function preflight() {
  return;
}

async function inspectPath(id, targetPath) {
  const target = targetPath;
  const exists = Boolean(await readTextIfExists(target));
  const content = exists ? (await readTextIfExists(target)) || '' : '';
  return {
    id,
    target,
    exists,
    threadlineManaged: /Threadline|THREADLINE_MANAGED|threadline/.test(content),
  };
}
