import path from 'node:path';
import { copyDir, ensureDir, readTextIfExists, upsertManagedBlock, writeTextIfChanged } from '../../utils/fs.mjs';
import { readTemplate } from '../../core/templates.mjs';

export const id = 'cursor';
export const name = 'Cursor';
export const homeDir = '~/.cursor';
export const supports = { skills: true, commands: false, config: true };

export async function installSkills(sourceDir, { replace = false } = {}) {
  const targetDir = path.join(homeDir, 'skills', path.basename(sourceDir));
  await ensureDir(path.dirname(targetDir));
  return copyDir(sourceDir, targetDir);
}

export async function installCommands() {
  return [];
}

export async function installConfig({ replace = false } = {}) {
  const configPath = path.join(homeDir, 'config.toml');
  const managed = `# Threadline-managed config for Cursor\n# Cursor rules and project context are generated by Threadline.\n`;
  if (replace) {
    return [await writeTextIfChanged(configPath, managed.trimEnd() + '\n')];
  }
  return [await upsertManagedBlock(configPath, 'THREADLINE_MANAGED', managed)];
}

export async function adopt() {
  const findings = [];
  findings.push(await inspectPath('cursor-skill', path.join(homeDir, 'skills', 'threadline', 'SKILL.md')));
  findings.push(await inspectPath('cursor-config', path.join(homeDir, 'config.toml')));
  return findings;
}

export async function preflight() {
  return;
}

async function inspectPath(id, targetPath) {
  const target = targetPath;
  const exists = Boolean(await readTextIfExists(target));
  const content = exists ? (await readTextIfExists(target)) || '' : '';
  return {
    id,
    target,
    exists,
    threadlineManaged: /Threadline|THREADLINE_MANAGED|threadline/.test(content),
  };
}
